---
title: "PlotBiases"
output: html_document
date: "2026-01-20"
---


```{r}
library(here)
library(tidyverse)
library(tidytext)
library(ggrepel)
```


The code for calculating lexical category biases is based on:
https://github.com/langcog/wordbank-book/blob/master/011-categories-syntactic.Rmd

You will also need the dependencies in:
https://github.com/langcog/wordbank-book/blob/master/_common.R


# Preparation

```{r}
bias_raw <- readr::read_csv(here("Data", "bias_WS_Ref_TotalVocab_2025Jun18.csv"), show_col_types = FALSE)
feat_raw <- readr::read_csv(here("Data", "LinguisticFeatures.csv"), show_col_types = FALSE)

bias <- bias_raw %>% mutate(
  language = str_squish(language),
  form     = str_squish(form),
  lexical_class = str_squish(lexical_class),
  measure  = str_squish(measure))
feat <- feat_raw %>% mutate(language = str_squish(language))

langs_in_feat <- feat %>% distinct(language, Family2, predicativeAdj)

bias_ws <- bias %>% filter(form == "WS") %>%
  inner_join(langs_in_feat, by = "language") %>% 
  subset(lexical_class != "Function Words")

# Check
bias_ws %>% count(lexical_class, measure) %>%
  arrange(desc(n)) %>%
  print(n = Inf)

bias_ws %>% count(language, lexical_class) %>%
  filter(n > 1)
```



# Visualization

```{r}
lexical_cols <- c(
  "Nouns"      = "#0072B2",
  "Verbs"      = "#009E73",
  "Adjectives" = "#D55E00")

df_plot <- bias_ws %>%
  filter(measure == "produces",
    form_type == "WS",
    lexical_class %in% c("Nouns", "Verbs", "Adjectives")) %>%
  mutate(
    lexical_class = factor(lexical_class, levels = c("Nouns","Verbs","Adjectives")),
    language_r = tidytext::reorder_within(language, mean, lexical_class))

ggplot(df_plot, aes(x = mean, y = language_r, color = lexical_class)) +
  geom_linerange(aes(xmin = ci_lower, xmax = ci_upper),
                 linewidth = 0.65, alpha = 0.95) +
  geom_point(size = 2.1) +
  geom_vline(xintercept = 0, linetype = "dashed",
             linewidth = 0.75, color = "grey35") +
  facet_wrap(~ lexical_class, nrow = 1, scales = "free") +
  tidytext::scale_y_reordered() +
  scale_color_manual(values = lexical_cols, guide = "none") +
  scale_x_continuous(
    breaks = seq(-0.2, 0.1, 0.04),
    minor_breaks = seq(-0.2, 0.1, 0.02),
    expand = expansion(mult = c(0.01, 0.02))) +
  labs(y = NULL, x = "Lexical category bias (productive vocabulary)") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid.major.y = element_line(linewidth = 0.15, color = "grey85"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(linewidth = 0.25, color = "grey87"),
    panel.grid.minor.x = element_blank(),
    strip.text = element_text(face = "bold", size = 16),
    strip.background = element_rect(fill = "grey90", color = NA),
    axis.text.y = element_text(size = 13, color="gray15", lineheight = 0.92, margin = margin(r = 1)),
    axis.text.x = element_text(size = 12.5, color="gray15"),
    axis.title.x = element_text(size = 13.5, color="gray15", face = "bold", margin = margin(t = 2)),
    axis.ticks.x = element_blank(),
    panel.spacing.x = unit(5, "pt"),
    plot.margin = margin(4, 4, 4, 4))
ggsave(here("Figures", "lexcat_bias.png"), width = 13, height = 7.4, dpi = 320, bg = "white")
```



```{r}
df_wide <- bias_ws %>%
  filter(
    measure == "produces",
    form_type == "WS",
    lexical_class %in% c("Nouns", "Verbs", "Adjectives")) %>%
  select(language, lexical_class, mean, predicativeAdj) %>%
  pivot_wider(
    names_from = lexical_class,
    values_from = mean)

axis_lim <- range(df_wide %>% select(Nouns, Verbs, Adjectives), na.rm = TRUE)
axis_lim <- max(abs(axis_lim))
axis_lim <- ceiling(axis_lim * 10) / 10


ggplot(df_wide, aes(x = Nouns, y = Verbs)) +
  geom_hline(yintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_vline(xintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_abline(slope = -1, intercept = 0, 
              linetype = "dotted", linewidth = 0.6, color = "grey40") +
  geom_smooth(method="lm", se=TRUE, color = "gray70", fill = "gray90") +
  geom_point(color = lexical_cols["Verbs"], size = 2.2) +
  geom_text_repel(
    aes(label = language),
    size = 3,
    max.overlaps = Inf,
    box.padding = 0.25,
    point.padding = 0.2,
    segment.color = "grey70") +
  labs(
    x = "Nouns (relative representation)",
    y = "Verbs") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.title = element_text(face = "bold"))


ggplot(df_wide, aes(x = Nouns, y = Adjectives)) +
  geom_hline(yintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_vline(xintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_abline(slope = -1, intercept = 0,
              linetype = "dotted", linewidth = 0.6, color = "grey40") +
  geom_smooth(method="lm", se=TRUE, color = "gray70", fill = "gray90") +
  geom_point(color = lexical_cols["Adjectives"], size = 2.2) +
  geom_text_repel(
    aes(label = language),
    size = 3,
    max.overlaps = Inf,
    box.padding = 0.25,
    point.padding = 0.2,
    segment.color = "grey70") +
  labs(
    x = "Nouns (relative representation)",
    y = "Adjectives") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.title = element_text(face = "bold"))


ggplot(df_wide, aes(x = Nouns, y = Adjectives, color = predicativeAdj)) +
  geom_hline(yintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_vline(xintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_abline(slope = -1, intercept = 0,
              linetype = "dotted", linewidth = 0.6, color = "grey40") +
  geom_smooth(method="lm", se=TRUE, fill = "gray90") +
  geom_point(size = 2.2) +
  geom_text_repel(
    aes(label = language),
    size = 3,
    max.overlaps = Inf,
    box.padding = 0.25,
    point.padding = 0.2,
    segment.color = "grey70") +
  labs(
    x = "Nouns (relative representation)",
    y = "Adjectives") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.title = element_text(face = "bold"))


ggplot(df_wide, aes(x = Verbs, y = Adjectives)) +
  geom_hline(yintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_vline(xintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_abline(slope = 1, intercept = 0,
              linetype = "dotted", linewidth = 0.6, color = "grey40") +
  geom_smooth(method="lm", se=TRUE, color = "gray70", fill = "gray90") +
  geom_point(color = lexical_cols["Nouns"], size = 2.2) +
  geom_text_repel(
    aes(label = language),
    size = 3,
    max.overlaps = Inf,
    box.padding = 0.25,
    point.padding = 0.2,
    segment.color = "grey70") +
  labs(
    x = "Verbs (relative representation)",
    y = "Adjectives") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.title = element_text(face = "bold"))


ggplot(df_wide, aes(x = Verbs, y = Adjectives, color = predicativeAdj)) +
  geom_hline(yintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_vline(xintercept = 0, linewidth = 0.4, color = "grey60") +
  geom_abline(slope = 1, intercept = 0,
              linetype = "dotted", linewidth = 0.6, color = "grey40") +
  geom_smooth(method="lm", se=TRUE, fill = "gray90") +
  geom_point(size = 2.2) +
  geom_text_repel(
    aes(label = language),
    size = 3,
    max.overlaps = Inf,
    box.padding = 0.25,
    point.padding = 0.2,
    segment.color = "grey70") +
  labs(
    x = "Verbs (relative representation)",
    y = "Adjectives") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.title = element_text(face = "bold"))


cor.test(df_wide$Nouns, df_wide$Verbs)
cor.test(df_wide$Nouns, df_wide$Adjectives)
cor.test(df_wide$Verbs, df_wide$Adjectives)

df_tmp <- df_wide %>% subset(predicativeAdj=="Present")
cor.test(df_tmp$Nouns, df_tmp$Adjectives)
cor.test(df_tmp$Verbs, df_tmp$Adjectives)

df_tmp <- df_wide %>% subset(predicativeAdj!="Present")
cor.test(df_tmp$Nouns, df_tmp$Adjectives)
cor.test(df_tmp$Verbs, df_tmp$Adjectives)
```

